# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Rujbin N.
"""OpenSSH-Bootstrap und Remotezugriffs-Workflows."""

from __future__ import annotations

from ._dependencies import (
    Any,
    Path,
    ThreadPoolExecutor,
    argparse,
    as_completed,
    base64,
    datetime,
    getpass,
    hashlib,
    ipaddress,
    json,
    os,
    re,
    secrets,
    shutil,
    socket,
    ssl,
    subprocess,
    sys,
    tempfile,
    time,
    timezone,
    urllib,
    yaml,
)

from .openssh_keys import (
    _public_key_summary,
    _known_hosts_lookup_name,
    _known_host_present,
    _ssh_host_key_port,
    _fingerprint_known_host_line,
    ensure_ssh_host_key,
    cmd_ssh_keygen,
)

from .openssh_scripts import (
    _powershell_single_quote,
    _windows_msi_path_for_ssh_guide,
    _ssh_bootstrap_ps1,
    _software_local_and_windows_path,
)

from .openssh_bootstrap import (
    _bootstrap_settings,
    _bootstrap_setup_instruction,
    _atomic_write_bytes,
    _atomic_copy_file,
    _sha256_file,
    _bootstrap_pki_paths,
    _bootstrap_launcher_roots,
    _root_command,
    _install_bootstrap_server_packages,
    _bootstrap_operator_ids,
    _nginx_quote,
    _openssl_server_config,
    _create_or_reuse_bootstrap_ca,
    _archive_bootstrap_root_ca,
    _controller_bound_bootstrap_root_certificates,
    _issue_bootstrap_server_certificate,
    _nginx_bootstrap_config,
    _configure_bootstrap_firewall,
    _trust_bootstrap_ca_locally,
    _enable_and_reload_nginx,
    _tcp_port_is_bindable,
    _tcp_listener_process_names,
    _managed_nginx_is_active,
    _bootstrap_url_with_port,
    _persist_bootstrap_base_url,
    _select_usable_bootstrap_port,
    _relaunch_bootstrap_server_setup_as_root,
    cmd_ssh_server_setup,
    _ensure_automatic_https_server,
    _RejectBootstrapRedirects,
    _strict_https_probe,
    _https_ssh_bootstrap_cmd,
    _deliver_ssh_launcher_to_public_desktop,
    _publish_https_ssh_bootstrap,
)

from .openssh_commands import (
    _local_windows_authenticode_status,
    cmd_ssh_setup_check,
    cmd_ssh_guide,
    cmd_ssh_use,
)

from .openssh_winrm import (
    cmd_ssh_winrm_https,
    _winrm_reset_root_identity,
    _winrm_leaf_fqdn_for_host,
    _bootstrap_state_thumbprints,
    _verified_bootstrap_root_thumbprints,
    cmd_ssh_winrm_reset,
    cmd_ssh_use_psrp,
)

from .openssh_cleanup import (
    _public_key_prefix_from_path,
    _public_key_prefix_from_text,
    _public_key_prefix_for_private_key,
    _ssh_private_key_path_for_host,
    cmd_ssh_remove_keys,
    ssh_remove_keys_menu,
)

from .openssh_audit import (
    _parse_ansible_core_version,
    _remote_management_disabled_state,
    _stored_bootstrap_root_thumbprints,
    _host_known_ca_thumbprints,
    _winrm_root_certificate_der_base64_for_thumbprint,
    _certificate_expiry_text,
    _print_certificate_metadata,
    _audit_value,
    _audit_nonnegative_count,
    _audit_service_is_disabled_or_absent,
    _audit_service_state_is_unknown,
    _classify_remote_management_audit,
    _inventory_remote_management_status,
    _remote_management_audit_play,
    _extract_remote_management_audit_result,
    _print_live_audit_certificate_metadata,
    _live_audit_transport_options,
    cmd_ssh_status,
)

from .openssh_menu import (
    ssh_menu,
)


from .openssh_lifecycle import (
    _archive_bootstrap_pki_for_rotation,
    _bootstrap_instance_id,
    _certificate_sha1_thumbprint,
    _certificate_valid_for,
    _mavi_public_key_prefix,
    _openssh_artifact_instance_id,
    _openssh_config_backup_relative_path,
    _openssh_firewall_rule_name,
    _remove_bootstrap_firewall,
    _remove_mavi_ssh_keys_from_host,
    _ufw_delete_tagged_rules,
    _untrust_bootstrap_ca_locally,
)

__all__ = (
    "_public_key_summary",
    "_known_hosts_lookup_name",
    "_known_host_present",
    "_fingerprint_known_host_line",
    "ensure_ssh_host_key",
    "cmd_ssh_keygen",
    "_powershell_single_quote",
    "_windows_msi_path_for_ssh_guide",
    "_ssh_bootstrap_ps1",
    "_software_local_and_windows_path",
    "_bootstrap_settings",
    "_bootstrap_setup_instruction",
    "_atomic_write_bytes",
    "_atomic_copy_file",
    "_sha256_file",
    "_bootstrap_pki_paths",
    "_bootstrap_launcher_roots",
    "_root_command",
    "_install_bootstrap_server_packages",
    "_bootstrap_operator_ids",
    "_nginx_quote",
    "_openssl_server_config",
    "_create_or_reuse_bootstrap_ca",
    "_archive_bootstrap_root_ca",
    "_controller_bound_bootstrap_root_certificates",
    "_issue_bootstrap_server_certificate",
    "_nginx_bootstrap_config",
    "_configure_bootstrap_firewall",
    "_trust_bootstrap_ca_locally",
    "_enable_and_reload_nginx",
    "_tcp_port_is_bindable",
    "_tcp_listener_process_names",
    "_managed_nginx_is_active",
    "_bootstrap_url_with_port",
    "_persist_bootstrap_base_url",
    "_select_usable_bootstrap_port",
    "_relaunch_bootstrap_server_setup_as_root",
    "cmd_ssh_server_setup",
    "_ensure_automatic_https_server",
    "_RejectBootstrapRedirects",
    "_strict_https_probe",
    "_https_ssh_bootstrap_cmd",
    "_deliver_ssh_launcher_to_public_desktop",
    "_publish_https_ssh_bootstrap",
    "_local_windows_authenticode_status",
    "cmd_ssh_setup_check",
    "cmd_ssh_guide",
    "cmd_ssh_use",
    "cmd_ssh_winrm_https",
    "cmd_ssh_winrm_reset",
    "cmd_ssh_use_psrp",
    "cmd_ssh_remove_keys",
    "ssh_remove_keys_menu",
    "_parse_ansible_core_version",
    "cmd_ssh_status",
    "ssh_menu",
    "_bootstrap_instance_id",
    "_certificate_valid_for",
    "_certificate_sha1_thumbprint",
    "_archive_bootstrap_pki_for_rotation",
    "_ufw_delete_tagged_rules",
    "_remove_bootstrap_firewall",
    "_untrust_bootstrap_ca_locally",
    "_mavi_public_key_prefix",
    "_remove_mavi_ssh_keys_from_host",
)
